In [1]:
# Name    :  Suyog Dighe
# Roll no :  09
# Batch   :  T1
# Title   :  Pythonic Data Cleaning With pandas and NumPy  Performing Data Analysis Using Python

print("Hello")

Hello

In [4]:
# import the library
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:
df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [7]:
df["Amount"].is_unique
df["Time"].is_unique

False

In [13]:
 df = df.set_index("Amount")

In [14]:
 df.head(10)

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
Amount,,,,,,,,,,,,,,,,,,,,,
149.62,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0
2.69,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0
378.66,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0
123.50,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0
69.99,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0
3.67,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,-0.371407,...,0.084968,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,0
4.99,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,-0.099254,...,-0.219633,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,0
40.80,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,1.249376,...,-0.156742,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,0
93.20,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,-0.410430,...,0.052736,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,0
3.68,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,-0.366846,...,0.203711,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,0

In [16]:
df.loc[20]

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
Amount,,,,,,,,,,,,,,,,,,,,,
20.0,1.431053,-0.648101,-0.331664,-1.207383,-0.012786,0.704440,-0.732126,0.183139,-0.878334,0.767906,...,0.100777,0.112749,0.222296,-0.244591,-1.688158,0.609778,-0.088366,0.010438,-0.014499,0
20.0,1.171439,0.474974,0.011761,1.264303,0.116234,-0.865986,0.554393,-0.276375,-0.471302,0.029104,...,-0.119439,0.070051,0.278843,-0.097491,0.426278,0.744938,-0.274728,0.008472,0.015492,0
20.0,0.075750,1.026986,0.834891,1.208913,0.107554,0.465977,-0.330959,-1.619873,-0.436604,0.060715,...,-0.258697,1.490696,-0.532414,-0.179765,-0.422717,0.774770,-0.172429,0.265078,0.230016,0
20.0,-1.064559,0.432452,0.128327,-2.019741,0.014434,-0.487552,0.293956,0.087702,-0.473573,1.350467,...,0.398423,0.112732,0.667153,-0.092997,-0.533060,0.003726,-0.271817,0.689156,0.480554,0
20.0,-0.119290,-0.072673,0.954166,-1.748743,-0.629337,-0.262410,-0.107887,-1.046362,-2.774309,1.689599,...,-0.411975,0.741758,0.253105,-0.015319,0.201732,-0.428462,-0.108378,0.046545,-0.084813,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20.0,-0.880549,0.618604,0.662090,-1.306761,0.769503,-0.272950,0.596708,-0.781758,0.121418,-0.969693,...,-0.418729,0.924232,0.406432,-0.393118,-0.349186,0.370851,0.120779,0.149925,0.091885,0
20.0,1.930085,-0.189980,-0.886533,0.137063,-0.216952,-0.281520,-0.534653,0.110034,0.956742,-0.562520,...,-0.088075,-0.201365,-0.508605,0.381548,0.640567,-0.511347,-0.341739,0.015044,-0.008724,0
20.0,-6.402301,3.528288,-1.387343,-1.363352,-0.890379,5.284838,-2.660357,3.061775,3.399814,5.637976,...,1.804931,-0.930063,-0.175417,-0.202516,0.635405,1.410258,-0.210797,0.571384,-0.259782,0
20.0,2.020989,0.706524,-2.841595,0.812181,0.836207,-2.021954,0.725502,-0.510672,0.450757,-1.487897,...,-0.119204,-0.063240,0.024090,-0.054270,-0.219004,0.378141,-0.522403,0.031119,0.018112,0
20.0,1.934225,-0.211828,-0.555074,0.999015,0.036366,0.576082,-0.560875,0.234023,0.694224,0.315757,...,-0.168548,-0.157641,-0.426007,0.301310,0.016217,-0.307245,-0.955430,0.045886,-0.031349,0

In [19]:
df.dtypes.value_counts()

float64    28
int64       1
dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Float64Index: 284807 entries, 149.62 to 217.0
Data columns (total 29 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   V1      284807 non-null  float64
 1   V2      284807 non-null  float64
 2   V3      284807 non-null  float64
 3   V4      284807 non-null  float64
 4   V5      284807 non-null  float64
 5   V6      284807 non-null  float64
 6   V7      284807 non-null  float64
 7   V8      284807 non-null  float64
 8   V9      284807 non-null  float64
 9   V10     284807 non-null  float64
 10  V11     284807 non-null  float64
 11  V12     284807 non-null  float64
 12  V13     284807 non-null  float64
 13  V14     284807 non-null  float64
 14  V15     284807 non-null  float64
 15  V16     284807 non-null  float64
 16  V17     284807 non-null  float64
 17  V18     284807 non-null  float64
 18  V19     284807 non-null  float64
 19  V20     284807 non-null  float64
 20  V21     284807 non-null  float64
 21  V22     284807 non-null  float64
 22  V23     284807 non-null  float64
 23  V24     284807 non-null  float64
 24  V25     284807 non-null  float64
 25  V26     284807 non-null  float64
 26  V27     284807 non-null  float64
 27  V28     284807 non-null  float64
 28  Class   284807 non-null  int64
dtypes: float64(28), int64(1)
memory usage: 73.2 MB

In [22]:
to_drop = ['V5',
            'V12',
            'V15']
df.drop(to_drop, inplace=True, axis=1)

In [23]:
df.head()

,V1,V2,V3,V4,V6,V7,V8,V9,V10,V11,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
Amount,,,,,,,,,,,,,,,,,,,,,
149.62,-1.359807,-0.072781,2.536347,1.378155,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0
2.69,1.191857,0.266151,0.166480,0.448154,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0
378.66,-1.358354,-1.340163,1.773209,0.379780,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0
123.50,-0.966272,-0.185226,1.792993,-0.863291,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0
69.99,-1.158233,0.877737,1.548718,0.403034,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0

In [24]:
df.rename(columns={"V1": "Person1"}, inplace=True)

In [25]:
df.head()

,Person1,V2,V3,V4,V6,V7,V8,V9,V10,V11,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Class
Amount,,,,,,,,,,,,,,,,,,,,,
149.62,-1.359807,-0.072781,2.536347,1.378155,0.462388,0.239599,0.098698,0.363787,0.090794,-0.551600,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,0
2.69,1.191857,0.266151,0.166480,0.448154,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,1.612727,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,0
378.66,-1.358354,-1.340163,1.773209,0.379780,1.800499,0.791461,0.247676,-1.514654,0.207643,0.624501,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,0
123.50,-0.966272,-0.185226,1.792993,-0.863291,1.247203,0.237609,0.377436,-1.387024,-0.054952,-0.226487,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,0
69.99,-1.158233,0.877737,1.548718,0.403034,0.095921,0.592941,-0.270533,0.817739,0.753074,-0.822843,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,0

In [29]:
print("Number of columns in df:", len(df.columns))

Number of columns in df: 26

In [30]:
print("End")

End